---
abstract: 'PoCo-IKC and PoCo-IRC based irc bot.'
author:
  - 'Yuji Suzuki <yujisuzuki@mail.arbolbell.jp>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POEIKC-Plugin-IRC
no_index:
  directory:
    - inc
    - t
recommends:
  POEIKC: 0
requires:
  Class::Inspector: 0
  POE: 0
  POE::Component::IKC::ClientLite: 0
  POE::Component::IRC: 0
  POE::Sugar::Args: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.00_01
